### ISSUE TITLE
Support to build Neovim from source

### ISSUE THREAD

**Issue by kkoomen** [rhysd/action-setup-vim#7]
Hi,

First of all, props for the plugin. Really useful for myself.

<hr />

I am experiencing issues when running ubuntu-latest + v0.2.0 for neovim using the following workflow setup:

```yml
  linux_neovim:
    name: Linux Tests (NeoVim)
    strategy:
      matrix:
        os: [ubuntu-latest]
        neovim: [true]
        vim-version: [v0.2.0, stable]
        node-version: [10, 12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-save
      - run: npm run build:binary -- node${{ matrix.node-version }}-linux-x64
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.vim-version }}
          neovim: ${{ matrix.neovim }}
      - name: Run tests
        run: ./scripts/run-vader-tests.sh "${{ steps.neovim.outputs.executable }}"
```

The tests fail like so:

<img width="2208" alt="image" src="https://user-images.githubusercontent.com/10693490/96962615-c48fa700-1539-11eb-9cfb-9c4b51d0fa04.png">

It does make sense, because neovim added support for linux x64 at [v0.3.2](https://github.com/neovim/neovim/releases/tag/v0.3.2). Is there a way that I can still support v0.2.0? My plugin has a minimum version that's required for the users to have and I want to test against these versions.

Let me know what's possible or if there's an alternative I can do. Perhaps let it build from source instead of getting the linux64.tar.gz?
